// Generated by https://quicktype.io

export interface ICurso {
  id: number;
  attributes: ICursoAttributes;
}

export interface ICursoAttributes {
  titulo: string;
  contenido: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  imagen: Imagen;
}

export interface Imagen {
  data: DataCurso;
}

export interface DataCurso {
  id: number;
  attributes: DataCursoAttributes;
}

export interface DataCursoAttributes {
  name: string;
  alternativeText: null;
  caption: null;
  width: number;
  height: number;
  formats: Formats;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl: null;
  provider: string;
  provider_metadata: ProviderMetadata;
  createdAt: string;
  updatedAt: string;
}

export interface Formats {
  large: Large;
  small: Large;
  medium: Large;
  thumbnail: Large;
}

export interface Large {
  ext: string;
  url: string;
  hash: string;
  mime: string;
  name: string;
  path: null;
  size: number;
  width: number;
  height: number;
  provider_metadata: ProviderMetadata;
}

export interface ProviderMetadata {
  public_id: string;
  resource_type: string;
}
