// Generated by https://quicktype.io

export interface IPosts {
  id: number;
  attributes: IPostsAttributes;
}

export interface IPostsAttributes {
  titulo: string;
  contenido: string;
  url: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  imagen: Imagen;
}

export interface Imagen {
  data: DataPost;
}

export interface DataPost {
  id: number;
  attributes: DataPostAttributes;
}

export interface DataPostAttributes {
  name: string;
  alternativeText: null;
  caption: null;
  width: number;
  height: number;
  formats: FormatsPost;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl: null;
  provider: string;
  provider_metadata: ProviderMetadataPost;
  createdAt: string;
  updatedAt: string;
}

export interface FormatsPost {
  small: MediumPost;
  medium: MediumPost;
  thumbnail: MediumPost;
}

export interface MediumPost {
  ext: string;
  url: string;
  hash: string;
  mime: string;
  name: string;
  path: null;
  size: number;
  width: number;
  height: number;
  provider_metadata: ProviderMetadataPost;
}

export interface ProviderMetadataPost {
  public_id: string;
  resource_type: string;
}
